# Generated by Django 4.2.27 on 2026-01-28 12:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location', models.CharField(help_text='Starting location address', max_length=500)),
                ('pickup_location', models.CharField(help_text='Pickup location address', max_length=500)),
                ('dropoff_location', models.CharField(help_text='Dropoff location address', max_length=500)),
                ('current_location_lat', models.FloatField(blank=True, null=True)),
                ('current_location_lon', models.FloatField(blank=True, null=True)),
                ('pickup_location_lat', models.FloatField(blank=True, null=True)),
                ('pickup_location_lon', models.FloatField(blank=True, null=True)),
                ('dropoff_location_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_location_lon', models.FloatField(blank=True, null=True)),
                ('current_cycle_used_hours', models.FloatField(default=0, help_text='Hours already used in the 8-day cycle', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(70)])),
                ('total_distance_miles', models.FloatField(blank=True, null=True)),
                ('total_trip_duration_hours', models.FloatField(blank=True, null=True)),
                ('estimated_days', models.IntegerField(blank=True, null=True)),
                ('route_polyline', models.TextField(blank=True, help_text='Encoded route polyline', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stop_type', models.CharField(choices=[('rest', 'Rest Stop (10-hour off-duty)'), ('break', '30-Minute Break'), ('fuel', 'Fuel Stop'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff')], max_length=20)),
                ('location_name', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('arrival_time', models.DateTimeField(help_text='Expected arrival time')),
                ('departure_time', models.DateTimeField(help_text='Expected departure time')),
                ('duration_hours', models.FloatField(help_text='Stop duration in hours')),
                ('miles_from_start', models.FloatField(help_text='Miles from trip start')),
                ('miles_from_previous', models.FloatField(help_text='Miles from previous stop')),
                ('sequence', models.IntegerField(help_text='Order of this stop in the trip')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
                'ordering': ['trip', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ELDLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField(help_text='Date of this log entry')),
                ('start_time', models.TimeField(help_text='Start time of this status')),
                ('end_time', models.TimeField(help_text='End time of this status')),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=25)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('sequence', models.IntegerField(help_text='Order within the day')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eld_logs', to='trips.trip')),
            ],
            options={
                'verbose_name': 'ELD Log Entry',
                'verbose_name_plural': 'ELD Log Entries',
                'ordering': ['log_date', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DailyLogSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_date', models.DateField()),
                ('day_number', models.IntegerField(help_text='Day number of the trip (1, 2, 3...)')),
                ('driving_hours', models.FloatField(default=0)),
                ('on_duty_hours', models.FloatField(default=0)),
                ('off_duty_hours', models.FloatField(default=0)),
                ('sleeper_berth_hours', models.FloatField(default=0)),
                ('total_miles_driven', models.FloatField(default=0)),
                ('cycle_hours_remaining', models.FloatField(default=70)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='trips.trip')),
            ],
            options={
                'verbose_name': 'Daily Log Summary',
                'verbose_name_plural': 'Daily Log Summaries',
                'ordering': ['trip', 'day_number'],
                'unique_together': {('trip', 'log_date')},
            },
        ),
    ]
